In [1]:
import cv2
import numpy as np

In [5]:
path = "gray26opb"
ori_img = cv2.imread(path+'.png')
cv2.imshow("Original_Gray", ori_img)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(ori_img)
cpy_img = ori_img

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 ..., 
 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  ..., 
  [1 1 1]
  [1 1 1]
  [1 1 1]]]


In [10]:
print(ori_img.shape)
for i in range(0,360):
    for j in range(0,480):
        if(cpy_img[i,j,0] == 130):
            cpy_img[i,j,0] = 12
            cpy_img[i,j,1] = 12
            cpy_img[i,j,2] = 12

(360, 480, 3)


In [11]:
cv2.imshow("Original_Gray", ori_img)
cv2.imshow("Changed_Gray", cpy_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
path = "gray26opb"
ori_img = cv2.imread(path+'.png')
arr = np.array(ori_img)

In [42]:
np.savetxt('matrix-'+path+'-png.txt', arr, fmt='%s')

In [43]:
nx,ny,nz=np.shape(arr)
CXY=np.zeros([ny, nx])
for i in range(ny):
    for j in range(nx):
        CXY[i,j]=np.max(arr[j,i,:])

#Binary data
#np.save('0001TP_007590-gray-png.npy', CXY)

#Human readable data
np.savetxt('value-'+path+'-png.txt', CXY)

In [14]:
img_ori = cv2.imread('train/0006R0_f02280.png')
cv2.imshow("ax",img_ori)
cv2.waitKey(0)
gray_image = cv2.cvtColor(img_ori, cv2.COLOR_BGR2GRAY)

In [15]:
cv2.imshow("ax",gray_image)
cv2.waitKey(0)

255